

GET http://localhost:5037/api/clients


###
POST http://localhost:5037/api/clients
Content-Type: application/json

{
    "name":"Rifat",
    "email":"rifatbhuiyan01944@gmail.com",
    "phone":"01944163529",
    "address":"Narayanganj, Araihazar"
}
###
PUT http://localhost:5037/api/clients/81c4a25a-94bb-42d8-85c5-8b96bfbbf8f5
Content-Type: application/json

{
    "name":"Ratul",
    "email":"ratulbhuiyan01944@gmail.com",
    "phone":"01944163509",
    "address":"Dhaka, Mirpur"
}

###
DELETE  http://localhost:5037/api/clients/81c4a25a-94bb-42d8-85c5-8b96bfbbf8f5