

GET http://localhost:5037/api/clients


###
POST http://localhost:5037/api/clients
Content-Type: application/json

{
    "name":"Rifat",
    "email":"rifatbhuiyan01944@gmail.com",
    "phone":"01944163529",
    "address":"Narayanganj, Araihazar"
}
###
PUT http://localhost:5037/api/clients/1517c0c6-cbe6-4cc0-995f-b5f52a555237
Content-Type: application/json

{
    "name":"Ratul",
    "email":"ratulbhuiyan01944@gmail.com",
    "phone":"01944163509",
    "address":"Dhaka, Mirpur"
}

###
DELETE  http://localhost:5037/api/clients/1517c0c6-cbe6-4cc0-995f-b5f52a555237